### ISSUE TITLE
User can create a log

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/doggo-loggo#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose a category to log what the dog did for the day

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see a list of categories including one that can be customized, and can click the "ADD" button to add that category to their logs.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-05 at 2 53 10 PM](https://user-images.githubusercontent.com/85139853/132142388-391dc80f-dda7-41a2-84f4-8da191a32f2a.png)
![Screen Shot 2021-09-05 at 2 54 04 PM](https://user-images.githubusercontent.com/85139853/132142402-c856d954-378c-4711-9574-ec5de4c6d427.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to include the tables: `users`, `dogs`, `owners`, `photos`, and `logs`.
- [x] Create the database using `createdb` doggoLoggo.
- [x] Import the database schema with `npm run db:import`.
- [x] Check the database with `pgweb --db=doggoLoggo`.

### ☁️ Server

- [x] Set up a basic express server using the .env variables.
- [x] Set up `pgweb` for the database.
- [x] Update `server/index.js` to receive a `POST` request from the client.
- [x] Update `server/index.js` to insert data(the category chosen by the user) into the database using SQL.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a `link` for bootstrap and fontawesome in index.html.
- [x] Import necessary packages such as `react`, `react-dom`, `webpack`, etc.
- [x] Render a basic React Element onto the root `div`.
- [x] Create an array of objects with the list of categories the user can choose from. Each object includes an `id`, `name`, and `class` of the icon to be used.
- [x] Create a component for categories and set the initial state of `chosenCategory` to an empty string.
- [x] Update the component to render each item in the array with buttons, using `maps`.
- [x] Update the component to have a `handleClick` method for the buttons to be able to store which category was selected in the `chosenCategory` state.
- [x] Make sure to `bind` the method.
- [x] Update the component to have a `handleChange` method to store what is being typed in the `input` element of the customizable category.
- [x] Import the created component at app.jsx and render.
- [x] Update the handleClick method to control `POST` to add logs to the database.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
