### ISSUE TITLE
User can give a name to a dog

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/doggo-loggo#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can give a name to a dog.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will enter the name of their dog after logging in for the first time to be able to see the name of their dog show up on the home-screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-18 at 11 31 19 AM](https://user-images.githubusercontent.com/85139853/133902612-b0890260-916f-43ec-a48a-de01f6ad978d.png)
![Screen Shot 2021-09-18 at 11 31 51 AM](https://user-images.githubusercontent.com/85139853/133902899-a520a837-a4a3-4509-9de2-2f2f375ab135.png)
![Screen Shot 2021-09-18 at 11 36 13 AM](https://user-images.githubusercontent.com/85139853/133905132-2d7360a1-77df-478f-a076-78d0fdfc5493.png)
![Screen Shot 2021-09-18 at 11 36 30 AM](https://user-images.githubusercontent.com/85139853/133905145-015c73d8-af24-4045-bab4-691f0c9170dd.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have a dogName in the "dogs" table.

### ☁️ Server

- [x] Update `server/index.js` to have a `POST` route to send the name of the dog to the database.
- [x] Update `server/index.js` to have a SQL to add a new dogId  in the "dogs" table once a name is entered.
- [x] Make sure the new route is under the authorization middleware.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a NameForm component to have the user input the name of their dog.
- [x] Update the NameForm component to have a handleChange( ) to track the inputted dog's name.
- [x] Update the NameForm component to have a `POST` request/handleSubmit( ) to send the name of the dog to the database.
- [x] Make sure to the send the x-access-token in the header.
- [x] Update the Home component to have a fetch `GET` to get the dogName from the database.
- [x] Update the SignIn component so that the user is taken to the nameForm component upon valid sign-in for the first-time.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
