### ISSUE TITLE
User can add a new dog

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/doggo-loggo#18]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a new dog.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to choose "Add New Doggo" from the app-drawer and enter the name of the new dog to add a new dog.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-18 at 11 45 32 AM](https://user-images.githubusercontent.com/85139853/133905420-7bc652c2-db40-442a-ad5e-e572430cf80d.png)
![Screen Shot 2021-09-18 at 11 45 57 AM](https://user-images.githubusercontent.com/85139853/133905428-d6545395-09ca-4daa-abc6-c5e39a2d0772.png)
![Screen Shot 2021-09-18 at 11 48 22 AM](https://user-images.githubusercontent.com/85139853/133905486-68eac841-8cae-4154-98c6-1861d7c3a4cf.png)
![Screen Shot 2021-09-18 at 11 48 36 AM](https://user-images.githubusercontent.com/85139853/133905499-78548a98-498c-493f-9506-c6b326d62706.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to add a userId in the "owners" table upon adding a new dog.

### ⚡ Client

- [x] Add a "Add New Doggo" icon onto the app-drawer.
- [x] Create a new component to enter a new dog name to add a dog.
- [x] Set-up react-router to go to the add-dog-form when the "Add New Doggo" is clicked from the app-drawer.
- [x] Update new component so that a user can add a new dog by typing the new dog's name into the name-form.
- [x] Make sure a new dog is added in the database when a new dog's name is entered.
- [x] Make sure the correct name is getting retrieved from the database.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
