### ISSUE TITLE
User can view the current day's logs

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/doggo-loggo#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the logs

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will see the logs they added in the logs screen and will be able to toggle between the logs screen and the category-selection screen to be able to add more logs to the logs screen.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-05 at 2 58 01 PM](https://user-images.githubusercontent.com/85139853/132142474-09c73bb9-55c3-43c0-90ec-26a1eb914d42.png)
![Screen Shot 2021-09-05 at 2 58 23 PM](https://user-images.githubusercontent.com/85139853/132142477-18e5cc64-df22-43d4-b2f0-ca57ac73a7e0.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to `GET` the logs added by the user.
- [x] Create a SQL to `select` all of the logs from the current date in the database.
- [x] Respond with all of the logs.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Use `react-router-dom` to change windows between the category selection screen and the logs screen.
- [x] Create a component to show the current date and the `plus` button for toggling screens.
- [x] Add inner-white back-ground to the logs screen window.
- [x] Update the App component to have an initial `logs` state of `[ ]`.
- [x] Update the App component to have a `componentDidMount` method.
- [x] Update `componentDidMount`  to use fetch `GET` to get the logs from the server.
- [x] Then, once the response JSON is received and parsed, update the state with the received logs in app.jsx.
- [x] Render the received logs onto the logs screen.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
