### ISSUE TITLE
Polish

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/doggo-loggo#28]
## ✅ Task List

> ##### Commit checklist for tasks needed.

- [x] Add dummy config variables for AWS, etc.
- [x] Make sure the login page looks smooth without any text getting wrapped.
- [x] Remove pencil icon that lead to name-form
- [x] Change the size of app-drawer to 230px
- [x] Delete label on name form and replaced with header
- [x] Reverse the list of logs
