### ISSUE TITLE
User can sign up for an account

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/doggo-loggo#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign-up for an account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to enter a username and password to create their own account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-05 at 3 17 16 PM](https://user-images.githubusercontent.com/85139853/132142804-e36703ee-0efb-426d-b079-ccad8888e85b.png)
![Screen Shot 2021-09-05 at 3 17 40 PM](https://user-images.githubusercontent.com/85139853/132142812-5989d8f8-bf46-4ba1-8fb4-d7099f4efdb7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Install the argon2 package.
- [x] Update `server/index.js` to receive a `POST` request to `/api/users`.
- [x] Make sure an error is thrown if there were no username or password given.
- [x] Hash the user's password with `argon2.hash( )`.
- [x] Then, insert the user's "username" and "hashedPassword" into the "users" table.
- [x] Then, respond to the client with a 201 status code and the new user's "userId" and "username".
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a auth-form component to render the sign-up form which is to go in auth component.
- [x] Create a handleSubmit method for the username.
- [x] Create a handleChange method for the password.
- [x] Make sure the doggoLoggo logo is inserted.
- [x] Create a auth component to render the sign-up page.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
