### ISSUE TITLE
User can sign into their account

### ISSUE THREAD

**Issue by Richard-Watanabe** [Richard-Watanabe/doggo-loggo#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign into their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to enter their username and password entered during account creation to sign into their account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-05 at 3 19 52 PM](https://user-images.githubusercontent.com/85139853/132142858-6a403347-e922-46c1-9ae0-f3530844bf3b.png)
![Screen Shot 2021-09-05 at 3 20 03 PM](https://user-images.githubusercontent.com/85139853/132142860-8f46700b-3bbf-45f7-8590-33b4a572888f.png)
![Screen Shot 2021-09-05 at 3 20 15 PM](https://user-images.githubusercontent.com/85139853/132142868-fb95e70f-82c0-472a-b064-fc9052c002d1.png)
![Screen Shot 2021-09-05 at 3 20 33 PM](https://user-images.githubusercontent.com/85139853/132142878-144df25f-9bd2-4a57-91af-62932bc5d859.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Install jsonwebtoken.
- [x] Update `server/index.js` to have a `POST` route at `api/user` for sign-in.
- [x] Throw an error if a username or password is not given.
- [x] Write the SQL to `select` the `userId` and `hashedPassword` from the `users` table where `username` = `$1`.
- [x] Write the db.query to check if the provided `username` was found.
- [x] Use argon 2 to check if the provided `password` matches the `hashedPassword` in the database.
- [x] If it does not match, throw an error.
- [x] If it does match, sign a token and respond with the signed token.
- [x] Create and add an authorization middleware.
- [x] Update index.js to grab and show dog-specific data from the data-base.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update app.jsx to have the states `user`,  and `isAuthorizing`.
- [x] Add a parse-route.js to get the route after  the `/`.
- [x] Create a `handleSignIn( )` inside app.jsx to save a token in local storage once signed in.
- [x] Create a decode-token.js file to decode token at app.jsx.
- [x] Create the `componentDidMount( )` in app.jsx to check if a token exists in local storage.
- [x] Pass data to other components by making a  `AppContext`.
- [x] Create a sign-in.jsx for sign-in.
- [x] Create a sign-in-form.jsx for the sign-in-form.
- [x] Pass the token around with AppContext to send in fetch header.

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
